import { Lightbulb, AlertTriangle } from "lucide-react";

function AIRecommendations({ recommendations }) {

  if (!recommendations || recommendations.length === 0) return null;

  const getPriorityColor = (priority) => {

    switch (priority) {

      case "High":
        return {
          bg: "bg-red-500/10",
          border: "border-red-500/30",
          text: "text-red-400",
        };

      case "Medium":
        return {
          bg: "bg-yellow-500/10",
          border: "border-yellow-500/30",
          text: "text-yellow-400",
        };

      default:
        return {
          bg: "bg-green-500/10",
          border: "border-green-500/30",
          text: "text-green-400",
        };

    }

  };

  return (

    <div className="mt-10 rounded-3xl border border-zinc-800 bg-gradient-to-br from-[#18181B] to-[#111111] p-8">

      <div className="flex items-center gap-4">

        <div className="rounded-2xl bg-yellow-500/10 p-3">

          <Lightbulb
            size={28}
            className="text-yellow-400"
          />

        </div>

        <div>

          <h2 className="text-3xl font-bold text-white">
            AI Recommendations
          </h2>

          <p className="text-zinc-400 mt-1">
            Personalized improvements generated by CareerForge AI.
          </p>

        </div>

      </div>

      <div className="mt-8 space-y-5">

        {recommendations.map((item, index) => {

          const colors = getPriorityColor(item.priority);

          return (

            <div
              key={index}
              className={`rounded-2xl border ${colors.border} ${colors.bg} p-6`}
            >

              <div className="flex justify-between items-start">

                <div>

                  <h3 className="text-xl font-semibold text-white">
                    {item.title}
                  </h3>

                  <p className="mt-3 text-zinc-300">
                    {item.description}
                  </p>

                </div>

                <div
                  className={`rounded-full px-4 py-2 text-sm font-semibold ${colors.bg} ${colors.text}`}
                >
                  {item.priority}
                </div>

              </div>

            </div>

          );

        })}

      </div>

      <div className="mt-8 flex items-center gap-3 text-zinc-400">

        <AlertTriangle
          size={18}
          className="text-yellow-400"
        />

        <span>
          Complete the high-priority recommendations first.
        </span>

      </div>

    </div>

  );

}

export default AIRecommendations;